<template>
  <div v-loading="loading" class="settings-page art-full-height">
    <ElCard shadow="never" class="page-header"><div class="header-content"><div><h2>系统设置</h2><p>统一管理交易参数、风控策略与应用服务配置</p></div><div class="header-actions"><ElTag :type="editing ? 'warning' : 'success'" effect="light">{{ editing ? '编辑中' : '配置已生效' }}</ElTag><ElButton type="primary" @click="editing ? save() : (editing = true)">{{ editing ? '保存设置' : '编辑设置' }}</ElButton></div></div></ElCard>
    <ElCard shadow="never" class="panel trade"><template #header><SectionTitle mark="▣" color="blue" title="交易费率与交易时间" desc="设置不同市场的收费规则和交易时段" /></template><ElTabs class="market-tabs"><ElTabPane label="A股"><SettingsBlock :editing="editing" :data="setting.trade" :fields="tradeFields" /></ElTabPane><ElTabPane label="港股"><SettingsBlock :editing="editing" :data="setting.trade" :fields="tradeFields" /></ElTabPane></ElTabs></ElCard>
    <div class="grid"><ElCard shadow="never" class="panel"><template #header><SectionTitle mark="▣" color="green" title="杠杆和风控" desc="资金杠杆与强制平仓阈值" /></template><SettingsBlock :editing="editing" :data="setting.risk" :fields="riskFields" /></ElCard><ElCard shadow="never" class="panel"><template #header><SectionTitle mark="▣" color="red" title="充值提现" desc="充值档位、提现费用与限额" /></template><SettingsBlock :editing="editing" :data="setting.recharge" :fields="rechargeFields" /></ElCard><ElCard shadow="never" class="panel"><template #header><SectionTitle mark="▣" color="gray" title="买入涨幅限制" desc="不同板块买入限制与交易权限" /></template><SettingsBlock :editing="editing" :data="setting.limits" :fields="limitFields" /></ElCard><ElCard shadow="never" class="panel"><template #header><SectionTitle mark="⚙" color="blue" title="系统设置" desc="行情、客服与消息服务地址" /></template><SettingsBlock :editing="editing" :data="setting.links" :fields="linkFields" /></ElCard></div>
    <div v-if="editing" class="footer"><ElButton @click="cancel">取消</ElButton><ElButton type="primary" @click="save">保存设置</ElButton></div>
  </div>
</template>
<script setup lang="ts">
import { defineComponent } from 'vue'
import { ElMessage } from 'element-plus'
import { fetchAppSystemSetting, saveAppSystemSetting, type AppSystemSetting } from '@/api/system-manage'
import SettingsBlock from './SettingsBlock.vue'
defineOptions({name:'SettingsSystem'})
const SectionTitle=defineComponent({props:{mark:String,color:String,title:String,desc:String},template:'<div class="section-title"><span class="section-mark" :class="color">{{ mark }}</span><div><h3>{{ title }}</h3><p>{{ desc }}</p></div></div>'})
const loading=ref(false),editing=ref(false),snapshot=ref(''),setting=reactive<AppSystemSetting>({trade:{},risk:{},recharge:{},limits:{},links:{}})
const fields=(data:[string,string,any][])=>data.map(([key,label,type])=>({key,label,type}))
const tradeFields=fields([['buyCommission','买入佣金费率','number'],['sellCommission','卖出佣金费率','number'],['minCommission','最小佣金','number'],['stampDuty','印花税费率','number'],['transferFee','过户费率','number'],['managementFee','管理费率','number'],['morningStart','早上开始时间','time'],['morningEnd','早上结束时间','time'],['afternoonStart','下午开始时间','time'],['afternoonEnd','下午结束时间','time'],['allDay','全时段交易','boolean'],['nonTradingFee','非交易日收费','boolean']])
const riskFields=fields([['defaultLeverage','默认杠杆倍数','number'],['forceCloseRatio','强制平仓比例','number'],['appLeverageEnabled','App可用资金是否乘杠杆倍数','boolean']])
const rechargeFields=fields([['minRecharge','最小充值金额','number'],['quickAmounts','快捷充值档位','text'],['minWithdraw','最小提现金额','number'],['withdrawFeeRate','提现手续费率','number'],['minWithdrawFee','最小提现手续费','number'],['dailyWithdrawLimit','每日提现次数','number'],['withdrawStart','提现开始时间','time'],['withdrawEnd','提现结束时间','time'],['sameDaySellWithdraw','当天卖出的持仓金额需要次日才可以提现','boolean']])
const limitFields=fields([['starBoard','科创板买入限制','number'],['beijingBoard','北交所买入限制','number'],['mainBoard','主板买入限制','number'],['growthBoard','创业板买入限制','number'],['minStarShares','科创板最小买入股数','number'],['stTrade','ST股票交易','boolean'],['newStockTrade','N股（新股）交易','boolean']])
const linkFields=fields([['customerService','在线客服链接','text'],['hkdRate','港币汇率','number'],['aQuote','A股行情链接','text'],['hkQuote','港股行情链接','text'],['telegramToken','Telegram 密钥','text'],['telegramChatId','Telegram 群组 ID','text']])
const load=async()=>{loading.value=true;try{Object.assign(setting,await fetchAppSystemSetting());snapshot.value=JSON.stringify(setting)}finally{loading.value=false}}
const save=async()=>{await saveAppSystemSetting(setting);snapshot.value=JSON.stringify(setting);editing.value=false;ElMessage.success('系统设置已保存')}
const cancel=()=>{Object.assign(setting,JSON.parse(snapshot.value));editing.value=false};onMounted(load)
</script>
<style scoped>
.settings-page{height:auto;min-height:var(--art-full-height);padding:8px 0 28px;overflow:visible}.page-header{flex:none;margin-bottom:14px;border-radius:6px;overflow:visible}.page-header :deep(.el-card__body){min-height:82px;padding:18px 20px}.header-content{display:flex;align-items:center;justify-content:space-between;min-height:46px}.header-content h2{margin:0;line-height:1.35;font-size:18px}.header-content p,.section-title p{margin:5px 0 0;color:var(--el-text-color-secondary);font-size:12px;line-height:1.5}.header-actions{display:flex;flex:none;align-items:center;gap:12px}.panel{border-radius:6px}.trade{margin-bottom:14px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.market-tabs{padding:0 18px}.section-title{display:flex;align-items:center;gap:10px}.section-title h3{margin:0;font-size:15px}.section-mark{display:flex;flex:none;align-items:center;justify-content:center;width:26px;height:26px;border-radius:4px}.blue{color:#409eff;background:#ecf5ff}.green{color:#67c23a;background:#f0f9eb}.red{color:#f56c6c;background:#fef0f0}.gray{color:#909399;background:#f4f4f5}.footer{position:relative;z-index:1;display:flex;justify-content:flex-end;gap:10px;padding:14px 16px;margin-top:14px;background:#fff;border:1px solid #dcdfe6;border-radius:6px;box-shadow:0 2px 10px rgb(0 0 0 / 8%)}@media(max-width:900px){.header-content{align-items:flex-start;flex-direction:column;gap:12px}.grid{grid-template-columns:1fr}}
</style>
