<template>
  <div class="notice-page art-full-height">
    <ArtSearchBar v-model="filters" :items="searchItems" :show-expand="false" @search="search" @reset="reset" />
    <ElCard class="art-table-card"><ArtTableHeader :loading="loading" @refresh="load"><template #left><ElButton @click="openEditor()">添加公告</ElButton></template></ArtTableHeader>
      <ElTable v-loading="loading" :data="rows"><ElTableColumn type="selection" width="42"/><ElTableColumn prop="id" label="ID" width="70"/><ElTableColumn prop="title" label="公告标题" min-width="160"/><ElTableColumn label="公告内容" min-width="260"><template #default="{row}"><span class="content-preview">{{row.content}}</span></template></ElTableColumn><ElTableColumn label="是否弹窗" width="100"><template #default="{row}"><ElTag :type="row.popup?'success':'info'">{{row.popup?'是':'否'}}</ElTag></template></ElTableColumn><ElTableColumn label="通知用户" width="140"><template #default="{row}">{{recipientText(row)}}</template></ElTableColumn><ElTableColumn label="状态" width="100"><template #default="{row}"><ElSwitch :model-value="row.status===1" @change="toggleStatus(row)"/></template></ElTableColumn><ElTableColumn label="创建时间" min-width="165"><template #default="{row}">{{time(row.created_at)}}</template></ElTableColumn><ElTableColumn label="更新时间" min-width="165"><template #default="{row}">{{time(row.updated_at)}}</template></ElTableColumn><ElTableColumn label="操作" width="78" fixed="right"><template #default="{row}"><ElDropdown trigger="click"><ElButton text>操作</ElButton><template #dropdown><ElDropdownMenu><ElDropdownItem @click="openEditor(row)">编辑</ElDropdownItem><ElDropdownItem divided class="danger" @click="remove(row)">删除</ElDropdownItem></ElDropdownMenu></template></ElDropdown></template></ElTableColumn></ElTable>
      <div class="pager"><span>共 {{total}} 条</span><ElPagination v-model:current-page="page" v-model:page-size="pageSize" :total="total" layout="prev, pager, next, sizes" @current-change="load" @size-change="load" /></div>
    </ElCard>
    <ElDialog v-model="visible" :title="current?.id?'编辑公告':'添加公告'" width="760px"><ElForm label-width="100px"><ElFormItem label="公告标题" required><ElInput v-model="form.title" placeholder="请输入公告标题"/></ElFormItem><ElFormItem label="公告内容" required><ElInput v-model="form.content" type="textarea" :rows="5" placeholder="请输入公告内容"/></ElFormItem><ElFormItem label="是否弹窗"><ElSwitch v-model="form.popup"/></ElFormItem><ElFormItem label="通知用户"><ElSelect v-model="form.recipient_ids" multiple filterable allow-create default-first-option placeholder="请输入客户 ID，留空则通知所有用户" style="width:100%"><ElOption v-for="id in form.recipient_ids" :key="id" :label="`客户 #${id}`" :value="id"/></ElSelect><p class="hint">提示：留空则通知所有用户</p></ElFormItem><ElFormItem label="状态"><ElSwitch v-model="enabled" active-text="启用" inactive-text="停用"/></ElFormItem></ElForm><template #footer><ElButton @click="visible=false">取消</ElButton><ElButton type="primary" @click="save">确定</ElButton></template></ElDialog>
  </div>
</template>
<script setup lang="ts">
import { ElMessage, ElMessageBox } from 'element-plus'
import { deleteAppNotice, fetchAppNotices, saveAppNotice, updateAppNoticeStatus, type AppNotice } from '@/api/system-manage'
defineOptions({name:'SettingsNotice'})
const loading=ref(false),rows=ref<AppNotice[]>([]),total=ref(0),page=ref(1),pageSize=ref(20),filters=reactive({title:'',popup:'',status:''})
const searchItems=[{label:'公告标题',key:'title',type:'input',props:{placeholder:'请输入公告标题'}},{label:'是否弹窗',key:'popup',type:'select',props:{placeholder:'请选择是否弹窗',options:[{label:'是',value:'true'},{label:'否',value:'false'}]}},{label:'状态',key:'status',type:'select',props:{placeholder:'请选择状态',options:[{label:'启用',value:'1'},{label:'停用',value:'2'}]}}]
const load=async()=>{loading.value=true;try{const data=await fetchAppNotices({page:page.value,pageSize:pageSize.value,...filters});rows.value=data.records;total.value=data.total}finally{loading.value=false}};const search=()=>{page.value=1;load()};const reset=()=>{Object.assign(filters,{title:'',popup:'',status:''});page.value=1;load()};const time=(v:string)=>v?new Date(v).toLocaleString('zh-CN',{hour12:false}):'--';const recipientText=(row:AppNotice)=>{try{const ids=JSON.parse(row.recipient_ids||'[]');return ids.length?`${ids.length} 位用户`:'所有用户'}catch{return '所有用户'}}
const visible=ref(false),current=ref<AppNotice|null>(null),enabled=ref(true),form=reactive({title:'',content:'',popup:false,recipient_ids:[] as number[]})
const openEditor=(row?:AppNotice)=>{current.value=row||null;let ids:number[]=[];try{ids=row?JSON.parse(row.recipient_ids||'[]'):[]}catch{};Object.assign(form,{title:row?.title||'',content:row?.content||'',popup:row?.popup||false,recipient_ids:ids});enabled.value=(row?.status??1)===1;visible.value=true}
const save=async()=>{if(!form.title.trim()||!form.content.trim())return ElMessage.warning('请填写公告标题和内容');await saveAppNotice({id:current.value?.id,title:form.title.trim(),content:form.content.trim(),popup:form.popup,recipient_ids:form.recipient_ids,status:enabled.value?1:2});ElMessage.success('公告已保存');visible.value=false;load()};const toggleStatus=async(row:AppNotice)=>{await updateAppNoticeStatus(row.id,row.status===1?2:1);ElMessage.success('公告状态已更新');load()};const remove=async(row:AppNotice)=>{await ElMessageBox.confirm(`确定删除公告「${row.title}」吗？`,'删除公告',{type:'warning'});await deleteAppNotice(row.id);ElMessage.success('公告已删除');load()};onMounted(load)
</script>
<style scoped>.notice-page{display:flex;flex-direction:column;gap:12px}.art-table-card{flex:1}.content-preview{display:-webkit-box;overflow:hidden;line-height:1.6;-webkit-box-orient:vertical;-webkit-line-clamp:2}.pager{display:flex;justify-content:flex-end;align-items:center;gap:14px;padding-top:14px}.hint{margin:6px 0 0;color:var(--el-text-color-secondary);font-size:12px}.danger{color:var(--el-color-danger)}</style>
